# Generated by Django 5.0.6 on 2024-10-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elon_Baza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=500)),
                ('material_description', models.CharField(max_length=500)),
                ('material_price', models.CharField(max_length=500)),
                ('material_price_currency', models.CharField(default='UZS', max_length=500)),
                ('material_measure', models.CharField(max_length=500)),
                ('material_image', models.CharField(max_length=500)),
                ('material_amount', models.CharField(max_length=500)),
                ('material_amount_measure', models.CharField(max_length=500)),
                ('material_status', models.CharField(max_length=500)),
                ('material_created_date', models.CharField(max_length=500)),
                ('material_updated_date', models.CharField(max_length=500)),
                ('material_deactivated_date', models.CharField(max_length=500)),
                ('sertificate_blank_num', models.CharField(default='asd123', max_length=500)),
                ('sertificate_reestr_num', models.CharField(default='abs123', max_length=500)),
                ('material_owner', models.CharField(default='1', max_length=500)),
                ('company_name', models.CharField(max_length=500)),
                ('company_stir', models.CharField(max_length=500)),
                ('material_region', models.CharField(max_length=500)),
                ('material_district', models.CharField(max_length=500)),
            ],
        ),
    ]
