# Generated by Django 5.0.6 on 2024-10-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elon_baza',
            name='company_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='elon_baza',
            name='company_stir',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='elon_baza',
            name='material_amount',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='elon_baza',
            name='material_amount_measure',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='elon_baza',
            name='material_created_date',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='elon_baza',
            name='material_deactivated_date',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='elon_baza',
            name='material_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='elon_baza',
            name='material_district',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='elon_baza',
            name='material_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='elon_baza',
            name='material_measure',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='elon_baza',
            name='material_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='elon_baza',
            name='material_owner',
            field=models.CharField(blank=True, default='1', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='elon_baza',
            name='material_price',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='elon_baza',
            name='material_price_currency',
            field=models.CharField(blank=True, default='UZS', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='elon_baza',
            name='material_region',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='elon_baza',
            name='material_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='elon_baza',
            name='material_updated_date',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='elon_baza',
            name='sertificate_blank_num',
            field=models.CharField(blank=True, default='asd123', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='elon_baza',
            name='sertificate_reestr_num',
            field=models.CharField(blank=True, default='abs123', max_length=500, null=True),
        ),
    ]
